substitutions:
  device_description: Growatt Inverter
  friendly_name:  Growatt Inverter
  name: Growatt
  
esphome:
  name: growatt

esp8266:
  board: esp07s

logger:
  baud_rate: 0
# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: !secret ota_password
  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: "Yourpassword"

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

output:
  - id: light_blauw
    platform: gpio
    pin: 16
  - id: light_groen
    platform: gpio
    pin: 0
  - id: light_rood
    platform: gpio
    pin: 2

uart:
  id: mod_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  
modbus:
  id: modbus1
  uart_id: mod_bus
  
modbus_controller:
  - id: growatt
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10  

text_sensor:
  - platform: template
    name: "${name} Status"
    icon: mdi:eye
    entity_category: diagnostic
    lambda: |-
      if (id(status).state = 1) {
        return {"Normal"};
      } else if (id(status).state = 0)  {
        return {"Waiting"};
      } else {
        return {"Fault!"};
      }

sensor:
  - platform: modbus_controller
    address: 0
    register_type: "read"
    internal: true
    id: status
      
  - platform: modbus_controller
    name: "${name} DcPower"
    address: 1
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    entity_category: diagnostic
    icon: mdi:flash
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    
  - platform: modbus_controller
    name: "${name} DcVoltage"
    address: 3
    register_type: "read"
    unit_of_measurement: V
    device_class: voltage
    entity_category: diagnostic
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    
  - platform: modbus_controller
    name: "${name} DcInputCurrent"
    address: 4
    register_type: "read"
    unit_of_measurement: A
    device_class: current
    entity_category: diagnostic
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    
# Enable the 2 sensors below when you have a 2 string inverter and want to know the values of the separate strings
    
#   - platform: modbus_controller
#     name: "${name} Pv1 Power"
#     address: 5
#     register_type: "read"
#     unit_of_measurement: W
#     device_class: power
#     entity_category: diagnostic
#     icon: mdi:flash
#     value_type: U_DWORD
#     accuracy_decimals: 1
#     filters:
#     - multiply: 0.1

#   - platform: modbus_controller
#     name: "${name} Pv2 Power"
#     address: 9
#     register_type: "read"
#     unit_of_measurement: W
#     device_class: power
#     entity_category: diagnostic
#     icon: mdi:flash
#     value_type: U_DWORD
#     accuracy_decimals: 1
#     filters:
#     - multiply: 0.1
    
  - platform: modbus_controller
    name: "${name} AcFrequency"
    address: 13
    register_type: "read"
    unit_of_measurement: Hz
    entity_category: diagnostic
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.01
  
  - platform: modbus_controller
    name: "${name} AcVoltage"
    address: 14
    register_type: "read"
    unit_of_measurement: V
    device_class: voltage
    entity_category: diagnostic
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
  
  - platform: modbus_controller
    name: "${name} AcOutputCurrent"
    address: 15
    register_type: "read"
    unit_of_measurement: A
    device_class: current
    entity_category: diagnostic
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    
  - platform: modbus_controller
    name: "${name} AcPower"
    address: 16
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    
  - platform: modbus_controller
    name: "${name} EnergyToday"
    address: 26
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    
  - platform: modbus_controller
    name: "${name} EnergyTotal"
    address: 28
    register_type: "read"
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    
  - platform: modbus_controller
    name: "${name} Temperature"
    address: 32
    register_type: "read"
    unit_of_measurement: °C
    device_class: temperature
    entity_category: diagnostic
    icon: mdi:thermometer
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
